### ISSUE TITLE
Error: Connection refused: Not authorized

### ISSUE THREAD

**Issue by matteobart** [homebridge-plugins/homebridge-roomba2#88]
### Expected Behavior
Accessories should be showing up and working after setup

### Current Behavior
Getting console errors that make the roombas unable to connect to Homebridge.

### Steps to Reproduce (for bugs)
I don't think I am doing anything special here but I'm using a Roomba 900 series and a Braava M6.
 
### Versions

- **Homebridge**: 1.3.6
- **Node**:      v16.13.0
- **Plugin**:      homebridge-roomba2 v1.3.0-beta.10

Note about plugin version, I am getting the same issue on the most recent stable release:
1.2.2 - latest

### Configuration
For Braava M6:
```json
{
    "name": "Braava",
    "model": "m6",
    "blid": "***",
    "robotpwd": ":#:###:***",
    "ipaddress": "192.168.1.#",
    "dockContactSensor": true,
    "runningContactSensor": true,
    "binContactSensor": true,
    "dockingContactSensor": true,
    "stopBehaviour": "home",
    "accessory": "Roomba2"
}
```
For Roomba 900:
```json
{
    "name": "Roomba",
    "model": "900",
    "blid": "***",
    "robotpwd": ":#:#:***",
    "ipaddress": "192.168.1.#",
    "dockContactSensor": true,
    "runningContactSensor": true,
    "binContactSensor": true,
    "dockingContactSensor": true,
    "stopBehaviour": "home",
    "accessory": "Roomba2"
}
```

### Homebridge Log / Command Output

This is one of the errors below. I get a similar one for the Roomba as well. I can post that in the comments if needed, but they are both the same/similar issues. 
```
[11/21/2021, 3:24:47 PM] [Braava] DEBUG: Connected to Roomba in 1176ms
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Updating Braava On from undefined to 0
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Updating Braava Charging State from undefined to 1
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Updating Braava Battery Level from undefined to 100
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Updating Braava Status Low Battery from undefined to 0
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Updating Braava Dock Contact Sensor State from undefined to 0
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Updating Braava Running Contact Sensor State from undefined to 0
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Updating Braava Docking Contact Sensor State from undefined to 0
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Merged updated state {"timestamp":1637526288081,"batteryLevel":100,"running":false,"charging":true,"docking":false} => {"timestamp":1637526288081,"batteryLevel":100,"running":false,"charging":true,"docking":false}
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Merged updated state {"timestamp":1637526288113,"batteryLevel":100,"running":false,"charging":true,"docking":false} => {"timestamp":1637526288113,"batteryLevel":100,"running":false,"charging":true,"docking":false}
[11/21/2021, 3:24:48 PM] [Braava] Running status: Returning 0 (183ms old)
[11/21/2021, 3:24:48 PM] [Braava] Low Battery status: Returning 0 (187ms old)
[11/21/2021, 3:24:48 PM] [Braava] Battery level: Returning 100 (189ms old)
[11/21/2021, 3:24:48 PM] [Braava] Charging status: Returning 1 (191ms old)
[11/21/2021, 3:24:48 PM] [Braava] Bin status: Returning no value (193ms old)
[11/21/2021, 3:24:48 PM] [Braava] Dock status: Returning 0 (367ms old)
[11/21/2021, 3:24:48 PM] [Braava] Running status: Returning 0 (370ms old)
[11/21/2021, 3:24:48 PM] [Braava] Bin status: Returning no value (373ms old)
[11/21/2021, 3:24:48 PM] [Braava] Docking status: Returning 0 (376ms old)
[11/21/2021, 3:24:48 PM] [Braava] DEBUG: Merged updated state {"timestamp":1637526288979,"batteryLevel":100,"running":false,"charging":true,"docking":false} => {"timestamp":1637526288979,"batteryLevel":100,"running":false,"charging":true,"docking":false}
[11/21/2021, 3:24:49 PM] [Roomba] Running status: Returning no value due to timeout
[11/21/2021, 3:24:49 PM] [Roomba] Low Battery status: Returning no value due to timeout
[11/21/2021, 3:24:49 PM] [Roomba] Battery level: Returning no value due to timeout
[11/21/2021, 3:24:49 PM] [Roomba] Charging status: Returning no value due to timeout
[11/21/2021, 3:24:49 PM] [Roomba] Bin status: Returning no value due to timeout
[11/21/2021, 3:24:49 PM] [Roomba] Dock status: Returning no value due to timeout
[11/21/2021, 3:24:49 PM] [Roomba] Running status: Returning no value due to timeout
[11/21/2021, 3:24:49 PM] [Roomba] Bin status: Returning no value due to timeout
[11/21/2021, 3:24:49 PM] [Roomba] Docking status: Returning no value due to timeout
[11/21/2021, 3:24:50 PM] [Braava] DEBUG: Merged updated state {"timestamp":1637526290666,"batteryLevel":100,"running":false,"charging":true,"docking":false} => {"timestamp":1637526290666,"batteryLevel":100,"running":false,"charging":true,"docking":false}
[11/21/2021, 3:24:50 PM] Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/usr/lib/node_modules/homebridge-roomba2/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/usr/lib/node_modules/homebridge-roomba2/node_modules/mqtt/lib/client.js:350:12)
    at work (/usr/lib/node_modules/homebridge-roomba2/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/usr/lib/node_modules/homebridge-roomba2/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/usr/lib/node_modules/homebridge-roomba2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/lib/node_modules/homebridge-roomba2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/lib/node_modules/homebridge-roomba2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
[11/21/2021, 3:24:50 PM] Got SIGTERM, shutting down Homebridge...
```

I haven't seen any information on "Error: Connection refused: Not authorized". I'm hoping that this is an easy fix. 

Without knowing anymore, could is be because of a bad password? I omitted the trailing and leading spaces from the password, I assume that is intentional. The dorita command is outputted _interestingly_.

**Comment by JacobSyndeo** [comment]
Same issue here, with Roomba 675.

### Versions:
**Homebridge:** 1.3.6 (same)
**Node:** v16.13.0 (same)
**Plugin:** homebridge-roomba2 v1.2.2 (different, but as OP noted, it happens on this version as well)

### Config:
Assuming BLID is a 16-character hex string, and the password is of format `:[1 num]:[10 num]:[16 alphanum]`, here’s my config:
```
    "accessories": [
        {
            "name": "Roomba",
            "model": "Roomba 675",
            "blid": "****************",
            "robotpwd": ":*:**********:****************",
            "ipaddress": "10.0.0.27",
            "autoRefreshEnabled": false,
            "dockContactSensor": true,
            "runningContactSensor": true,
            "binContactSensor": true,
            "accessory": "Roomba2"
        }
    ]
```
### Logs:
```
[11/21/2021, 1:47:28 PM] Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:350:12)
    at work (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
[11/21/2021, 1:47:28 PM] Got SIGTERM, shutting down Homebridge...
[11/21/2021, 1:47:28 PM] [homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[11/21/2021, 1:47:28 PM] [homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://git.io/JtMGR for more info.
[11/21/2021, 1:47:28 PM] [homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[11/21/2021, 1:47:28 PM] [homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' was slow to respond! See https://git.io/JtMGR for more info.
[11/21/2021, 1:47:28 PM] [homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'Filter Change Indication' was slow to respond! See https://git.io/JtMGR for more info.
[11/21/2021, 1:47:28 PM] [homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'Contact Sensor State' was slow to respond! See https://git.io/JtMGR for more info.
[11/21/2021, 1:47:28 PM] [homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'Contact Sensor State' was slow to respond! See https://git.io/JtMGR for more info.
[11/21/2021, 1:47:28 PM] [homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'Contact Sensor State' was slow to respond! See https://git.io/JtMGR for more info.
[11/21/2021, 1:47:29 PM] Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:350:12)
    at work (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
[11/21/2021, 1:47:31 PM] Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:350:12)
    at work (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/homebridge/node_modules/homebridge-roomba2/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
[11/21/2021, 1:47:33 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/21/2021, 1:47:38 PM] [HB Supervisor] Restarting Homebridge...
```
And after the restart, this process continues ad infinitum unless I disable the plugin.

**Comment by karlvr** [comment]
@JacobSyndeo Could you please test this again with the latest version (1.3.1) of the plugin?

**Comment by matteobart** [comment]
@karlvr still seeing the issue 
`13/12/2022, 8:59:39 PM] Error
Connection refused: Not authorized at MqttClient. handleConnack(/u
sr/lib/node modules/homebridge-roomba2/node modules/mqtt/lib/client.js:920:15) at MgttClient.
handlePacket/us
r/lib/node modules/homebridge-roomba2/node modules/mgtt/lib/client.js:35
0:12) at work (/usr/lib/node modules/h
omebridge-roomba2/node modules/mgtt/lib/client.js:292:12) at Writable.writable.
write (/usr/lib/node modules/homebridge-roomba2/node modules/mgtt/lib/client.js:30
2:5)
at doWrite (/usr/lib/node module
/homebridge-roomba2/node modules/readable-stream/lib/ stream writable.jS: 428: 64)
at writeOrBuffer(/usr/lib/node
modules/homebridge-roomba2/node modules/readable-stream/lib/ stream writable.js:417:5)
at Writable.write (/usr/lib/node
modules/homebridge-roomba2/node modules/readable-stream/lib/ stream writable.js:334:11)
at TLSSocket.ondata (node: internal/streams/readable: 754: 22)
at TLSSocket.emit (node:events: 390:28) at addChunk (node: internal/strea
ms/readable:315:12)
at readableAddChunk (node: internal/streams/readable: 289: 9)
at TLSSocket.Readable.push (node
:internal/streams/readable:228:10
`

**Comment by ChristianThingKnudsen** [comment]
Anyone who has found a solution? 
I have the same issue on my Roomba 976

homebridge: v.1.5.0
node: v.16.14.0.
homebridge-roomba2: v. 1.3.1. (latest)

**Comment by almonde** [comment]
I'm still seeing this issue on 1.3.1.
Homebridge: v1.5.0
Nodejs: v16.16

Roomba i3

Homebridge running in a Synology Docker container.

**Comment by karlvr** [comment]
I'm still not sure what this issue was caused by. Perhaps re-test with the latest beta and report back results.
